name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group  # Ensure only one action runs at a time
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # You can use 'adopt', 'zulu', or other distributions as well
          cache: 'maven'  #

      - name: Build with Maven #guess will work FINAL 2
        run: mvn clean package  # Build the project and create the .jar file

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          TIGRIS_ACCESS_KEY: ${{ secrets.TIGRIS_ACCESS_KEY }}
          TIGRIS_BUCKET_NAME: ${{ secrets.TIGRIS_BUCKET_NAME }}
          TIGRIS_SECRET_KEY: ${{ secrets.TIGRIS_SECRET_KEY }}
          TIGRIS_URL: ${{ secrets.TIGRIS_URL }}
          DATASOURCE: ${{ secrets.DATASOURCE }}