name: Java CI

on:
  push:
    branches:
      - main  # Change to your default branch name
  pull_request:
    branches:
      - main  # Change to your default branch name

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '23'  # Set your Java version
          distribution: 'temurin'  # Use 'temurin' for the latest OpenJDK distribution

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Upload test results
        if: always()  # Ensures this runs even if the tests fail
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports  # Adjust the path based on your project structure